### ISSUE TITLE
allow overwrite of existing release?

### ISSUE THREAD

**Issue by tony-kerz** [helm/chart-releaser-action#23] opened 2020-05-07 07:16 UTC
occasionally, i will want to overwrite an existing release,
assuming this isn't an anti-pattern, subject to scorn and ridicule 😭,
would it be reasonable to allow that to happen with an opt-in flag instead of getting:

```
Error: error creating GitHub release: POST https://api.github.com/repos/my-org/my-repo/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```

**Comment by unguiculus** [comment] 2020-06-27 17:39
Overwriting an existing release is not something I'd like to encourage. If you want to do this at all, it should really be an exceptional case that can be handled manually.

**Comment by scottrigby** [comment] 2020-08-09 15:50
Underscoring what @unguiculus said, chart releases should be immutable – this is to ensure reproducible builds for end users. The digest hash created by `helm package` ensures this (for history fun, see this issue discussion: https://github.com/helm/helm/issues/3084).

You can however do this yourself using bare helm and git/github API commands, which is manual work but advisable since you will have to manually ensure the conditions are OK for doing this (for example there was no possibility that end users could have accessed the already published version, etc).

Therefor, as @unguiculus said, let's please not add the ability to bypass this in the action automation - closing this one 😅

**Closed by scottrigby** 2020-08-09 15:51 UTC

**Comment by cberg-aot** [comment] 2022-02-08 17:29
what do you do when developing a chart and need to rapidly iterate?

**Comment by tglaeser** [comment] 2022-11-29 18:58
And in this context, option `CR_SKIP_EXISTING` doesn't make much sense either as the job will always skip, in fact fail, if already existing. Instead the option rather allows to switch between *skip and fail* or *skip and succeed*, not very intuitive naming.
