### ISSUE TITLE
Doesn't delete chart from GH Pages if deleted from the repository

### ISSUE THREAD

**Issue by douglascamata** [helm/chart-releaser-action#24] opened 2020-05-13 14:53 UTC
I added a test chart to a repository to set things up and do some tests.

After I finished I delete the chart from the git repository.

I can though still see the chart in my `index.yaml` file and download it.

I don't have any suggestions, unfortunately, about how this process could work, because some release artefacts would have to be deleted. 🤔

**Comment by unguiculus** [comment] 2020-06-27 17:37
Deleting a release is not supported. You have to do this manually. Deleting releases is not something that we encourage. Even if you delete a chart you may want to keep existing releases.

**Comment by scottrigby** [comment] 2020-08-09 15:56
Correct, this is by design so that charts can be marked `deprecated` (and in future could become un-deprecated as needed).  See:
- https://helm.sh/docs/topics/charts/#deprecating-charts
- https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart
- https://github.com/helm/charts/blob/master/PROCESSES.md#un-deprecating-a-chart

If you wish to delete a chart, it's important to note that because of the above, aggregator hubs (for example hub.helm.sh and artifacthub.io) will continue to list the previous chart if it was not deprecated before deleting. See https://github.com/helm/charts/issues/23128 for details.

Closing this issue as this is by design.

**Closed by scottrigby** 2020-08-09 15:56 UTC
Labels: wontfix
