### ISSUE TITLE
Detecting changed files is broken in v1.1.0

### ISSUE THREAD

**Issue by aabouzaid** [helm/chart-releaser-action#61] opened 2020-11-08 23:25 UTC
Hello,

because of the latest change in v1.1.0, now `charts_dir` doesn't work with "." (current working directory)
https://github.com/helm/chart-releaser-action/blob/c3d308d0c55d41f25565d9db5534da82dd8b07d7/cr.sh#L228

This expression cannot be less than `2` that's why no changes detected in the current working directory.

```
$ echo $(( $(tr "/" "\n" <<< "." | wc -l) + 1 )) 
2
```

The `+ 1` should be removed.

**Comment by ohdearaugustin** [comment] 2020-11-19 19:37
I can confirm that issue.

**Comment by ravikrs** [comment] 2020-11-22 22:22
I also faced this issue after upgrading version to 1.1.0
Downgraded the chart-releaser-action version to 1.0.0 for now

**Comment by madchap** [comment] 2021-02-24 21:59
Still seems to be present in 1.2.0.

**Comment by monotek** [comment] 2021-03-07 13:04
Same here: https://github.com/monotek/zammad-helm/runs/2050548488?check_suite_focus=true

**Comment by unguiculus** [comment] 2021-06-28 19:25
Fixed in #83

**Closed by unguiculus** 2021-06-28 19:25 UTC
